repositories {
    mavenCentral()
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:2.3.2")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    implementation 'net.serenity-bdd:serenity-core:2.3.2'
    implementation 'net.serenity-bdd:serenity-junit:2.3.2'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.slf4j:slf4j-simple:1.7.30'
}

test {
    include '**/ScenarioTest.class'
}

gradle.startParameter.continueOnFailure = true